---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2023/6/30 20:04
---
-- 1.参数列表
-- 1.1 优惠劵id
local voucherId=ARGV[1]
-- 1.2 用户id
local userId=ARGV[2]
-- 1.3 订单id
local userId=ARGV[2]
-- 2 数据key
-- 2.1 库存key
local stockkey='seckill:stock:'..voucherId
-- 2.2 订单key
local orderkey='seckill:order:'..voucherId
-- 3.脚本业务
-- 3.1.判断库存是否充足 get stockkey
if(tonumber(redis.call('get',stockkey))<=0) then
--    ` 3.2 库存不足，返回1
    return 1
end
-- 3.2.判断用户是否下单 SISMEMEBER orderKey userId
if(redis.call('sismember',orderkey,userId)==1) then
--   3.3存在说明是重复下单，返回
    return 2
end
-- 3.4扣库存incrby stockkey -1
redis.call('incrby',stockkey,-1)
-- 3.5 下单(保存用户) sadd orderKey userId
redis.call('sadd',orderkey,userId)
-- 3.6 发送西欧安息队列中，XADD stream ,orders * k1 v1 k2 v2。。。。
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',id)
return 0


